### ISSUE TITLE
Bad enterMode

### ISSUE THREAD

**Issue by werker** [ryancramerdesign/InputfieldCKEditor#17]
The configuration of the enterMode has a flaw that causes some bugs like preventing someone from pasting particular formatted MS Word text.

The enterMode is set in PHP as follows:

```
        $config = array(
            ...
            'enterMode' => 'CKEDITOR.ENTER_P',
            ...
            );
```

The problem there is that json_encode puts that value in quotes:

```
"enterMode":"CKEDITOR.ENTER_P"
```

But it's really a constant and not a string. That leads to some rare errors.
You can't change that behaviour of json_encode, so I see two options at the moment:
- Change 'CKEDITOR.ENTER_P' to 1 (as this is the value of that constant, but this wouldn't be future proof in my eyes)
- Move that enterMode config somewhere else to prevent it from being processed by json_encode

**Comment by ryancramerdesign** [comment]
Thanks for the report and troubleshooting here. It looks like we've got a 3rd option, which is just to omit the enterMode entirely. The CKEditor docs seem to indicate that the default value for enterMode is CKEDITOR.ENTER_P, so just omitting it should solve the problem in a future proof way. I'm not really sure why we had it there in the first place. I will go ahead and add this here in the next version (today).

**Comment by werker** [comment]
The fix works for me.
