### ISSUE TITLE
Javascript errors in inline mode

### ISSUE THREAD

**Issue by bfncs** [ryancramerdesign/InputfieldCKEditor#7]
Hi Ryan,

sorry to bother you again, but when using the current version of the module in inline mode, I get a lot of strange JS errors like `Cannot read property 'br' of undefined` or `Cannot read property 'undefined' of undefined`.

There are no problems like this in my commit from PR #6, so the must somehow stem from the other changes you made in ed5b31e7e7ca68d3d7b70f20a8772296a6a19b10.

I'm going to look further into this in the next days.

**Comment by ryancramerdesign** [comment]
Hmm, I'm not seeing those JS errors here–what browser are you using? I'm in
the latest Chrome on Mac. I will try Firefox. I've actually made some more
updates to this module today (including upgrade to CKEditor 4.1.2), so will
go ahead and push them. Let me know if it makes any change? Thanks –Ryan

**Comment by ryancramerdesign** [comment]
One other thing to add: check to make sure you've got the update to the
MarkupHTMLPurifier module.

**Comment by bfncs** [comment]
Hey Ryan,

thanks a lot for taking care of this one!
I'm using latest stable Chrome (28.0.1500.63) on Ubuntu but the error is the same in latest stable Firefox (22.0). I pulled in the latest commits on the master branch for this module and MarkupHTMLPurifier but that didn't change anything.

I'll have to investigate into this further and will hopefully be able to provide you with some more information soon.

Edit: Do you have any idea if there is an easy way to get the unminified source of ckeditor.js (easy meaning without having to set up the built process)?

**Comment by bfncs** [comment]
After having figured out how to get a debugable (unminified JS) build of CKEditor itself (for those wondering: ckbuilder.jar has an option `--leave-js-unminified`), it would be great, if you could share your `build-config.js` and what else you used for your build, so I can replicate it and finally find that error. Thanks a lot in advance!

**Comment by ryancramerdesign** [comment]
The CKEditor that I have is actually just the one that came through when I
clicked "download" on the CKEditor site. I didn't manually build it.
http://ckeditor.com/download - I selected "full package". Once I grabbed
it, I copied the "pwimage" and "pwlink" directories into the CKEditor
plugins directory. I think that's all that's necessary to update a copy of
CKEditor for ProcessWire.

**Comment by bfncs** [comment]
Thanks a lot for considering this. I wasn't rely able to reproduce it and didn't ever run into these problems afterwards. This was most probably caused by some obscure local problem, so I'm closing it down.
